### ISSUE TITLE
Street data block_A & block_small captures only a small subset of images

### ISSUE THREAD

**Issue by JokerYan** [city-super/MatrixCity#23]
Thank you for the wonderful dataset. However, we have noticed that the block_A and block_small folders in the small city street data only include a very small subset of all the images in the "train" and "test" folder. 

Are block_A & block_small splitted by different criteria compared to the "small_city_road_down/horizon/outside/vertical" blocks?
Are there any other blocks like block_A that can be released?
Is training directly on the "small_city_road_down/horizon/outside/vertical" viable? Does it cause any problems according to your experience?

Thank you very much!

**Comment by yixuanli98** [comment]
"small_city_road_down/horizon/outside/vertical" is the division we make when marking the beginning and end of the road and rendering the images. We filter block_A&block_small from the whole dataset. The block_A has the same area with block_A of aerial data, where aerial data are divided into block A&B&C&D&E according to the building height. Because block-size street data can not be well modeled by one single model, we filter a smaller area block_small to do experiments, which covers a crossroad area. You can refer to section 4.3 and 4.4 for more details
