### ISSUE TITLE
关于big city的transforms.json咨询

### ISSUE THREAD

**Issue by smart4654154** [city-super/MatrixCity#37]
十分感谢你们的工作
small city数据中有pose文件夹，里面包含 transforms.json ，对我在nerfstudio中训练十分有用。
![image](https://github.com/user-attachments/assets/21eb0c25-dfd7-400c-8a1d-2270d976bd25)
但是big city数据中没有pose文件夹，没有 transforms.json 
![image](https://github.com/user-attachments/assets/3f52cedb-751e-4361-bf82-02068931de4a)
虽然big_city/aerial/train/big_high_block_1到6自带 transforms.json ，但是这个 transforms.json 格式不便于在nerfstudio中训练。
请问你们可以提供big city数据pose文件夹吗？或者我有什么办法可以利用transforms.json以开启训练（big_city/aerial/train/big_high_block_1到6自带 的）吗？
十分感谢

**Comment by yixuanli98** [comment]
We provide script in https://github.com/city-super/MatrixCity/blob/main/scripts/generate_split.py. You can refer to it.

**Comment by smart4654154** [comment]
十分感谢回复，根据你们的代码，我得知旋转矩阵R需要乘100，平移矩阵T需要除以100，生成新的[R|T]，然后才可以训练。
我阅读readme得知，The unit of position is m. And the rotation matrix needs to be multiplied by 100 to normalize it.但是这似乎没必要。
我的问题是，为什么不直接提供处理好的[R|T]，而是需要旋转矩阵R需要乘100，平移矩阵T需要除以100，请问这样做是有什么目的吗？十分感谢

**Comment by yixuanli98** [comment]
"transforms.json" is the original export pose file and we generate the train/test split from it for NeRF training.

**Comment by smart4654154** [comment]
十分感谢你的回复
"transforms.json" is the original export pose file意思是，原始导出的pose无法直接使用（即旋转矩阵R是真实的1/100，平移矩阵T是真实的100倍），所以需要再次处理：旋转矩阵R需要乘100，平移矩阵T需要除以100。请问是这样吗？

**Comment by BitCalSaul** [comment]
@smart4654154 Hi, thanks for your previous explanations on pose scaling.

When I try to take the 8 NDC frustum vertices (x,y ∈ {-1,1}, z = near/far) and back-project them to world space for one camera, all 8 points end up extremely close together in world coordinates. This suggests the frustum is almost degenerate.

I also found that this camera’s world_view_matrix and full_proj_transform are very ill-conditioned.

**My question:**

Do we need to normalize/scale the raw R and T from transforms_origin.json or transforms.json before computing world_view_matrix and full_proj_transform for 3DGS/NeRF?

You previously mentioned “multiply R by 100 and divide T by 100” — should this always be done for all cameras, and what is the reasoning behind this scaling?

Could the ill-conditioned projection be caused by missing this normalization?

Thanks!
