### ISSUE TITLE
Transform normal to cam space

### ISSUE THREAD

**Issue by Binyr** [city-super/MatrixCity#42]
Hi, below shows two example from small_city/street/train/small_city_road_down: 0930 and 1228. Different columns are rgb, normal in cam space; mask of pixels that norm of normal is not equal to 1. 
1. As can be seen in the image, the normal of ground is significantly different but from the rgb image, the two cameras seems to have a similar angle witg repsect to the ground. Is there anything wrong with the camera rotation?
2. Why there exists so many normal that norm is not equal to 1?

![image](https://github.com/user-attachments/assets/5835b4ae-e79a-4e55-b02a-eb075069f183)
![image](https://github.com/user-attachments/assets/26594ae2-4187-49bc-b608-3fe9a225e55b)

Thank you,
Yanrui

**Comment by yixuanli98** [comment]
Our normals are in the world coordinate. We provided script to read normal in [load_data.py](https://github.com/city-super/MatrixCity/blob/main/scripts/load_data.py), where we normalize the normal. An explanation is provided [Depth and Normal Map Note](https://github.com/city-super/MatrixCity?tab=readme-ov-file#depth-and-normal-map-note). 
For your case, these two cameras have a similar angle with respect to the ground, which means these two cameras have same pitch. Maybe you can check if the cameras of these two images have different yaw, which will also affect normal in camera space.

**Comment by SunYangtian** [comment]
@yixuanli98 It seems that the presented normal has been transferred into the camera space. Hence the different color should not be caused by the yaw of camera.  

By the way, I have tried the [load_normal function](https://github.com/city-super/MatrixCity/blob/main/scripts/load_data.py), and also convert it to the camera space, as illustrated below
![debug](https://github.com/user-attachments/assets/d37b0eea-55b0-41e9-994e-0c69d43e3ddb)
The color of ground normal is about (64,127,16), which means that the normal vector is about (-0.49, 0, -0.87). This is really strange since the y-axis normal of ground is 0 in camera space. 

Could you give some advices?

@Binyr  Have you solved this problem?

**Comment by SunYangtian** [comment]
The normal converting from depth and intrinsic is like this:  which is not accurate, but basically correct. So I guess there are something wrong in the loaded normal
![debug2](https://github.com/user-attachments/assets/f98de690-6817-4e42-8fab-ef48ab8dd736)

**Comment by yixuanli98** [comment]
> [@yixuanli98](https://github.com/yixuanli98) It seems that the presented normal has been transferred into the camera space. Hence the different color should not be caused by the yaw of camera.
> 
> By the way, I have tried the [load_normal function](https://github.com/city-super/MatrixCity/blob/main/scripts/load_data.py), and also convert it to the camera space, as illustrated below ![debug](https://github.com/user-attachments/assets/d37b0eea-55b0-41e9-994e-0c69d43e3ddb) The color of ground normal is about (64,127,16), which means that the normal vector is about (-0.49, 0, -0.87). This is really strange since the y-axis normal of ground is 0 in camera space.
> 
> Could you give some advices?
> 
> [@Binyr](https://github.com/Binyr) Have you solved this problem?


What code did you use to convert to camera coordinate system? What are your camera coordinate system and world coordinate system respectively?
