### ISSUE TITLE
Could you please provide the folder content structure?

### ISSUE THREAD

**Issue by CJCHEN1230** [city-super/MatrixCity#6]
Really nice work! Thanks for sharing the dataset. I need to download the depth/RGB image pair for data training. Because I'm limited by the size of my hard drive. Could you tell me the following question or provide the content structure.

1. What's the difference between big city and small city?
2. What's the difference between  "train" and "train_dense"?  I suppose all the data should be dense, because it's synthetic data.
3. Why there is no depth map in big city?

**Comment by yixuanli98** [comment]
Thanks for you suggestions! We will update the folder content structure soon.
1. Small city has an area of about 2.7 km^2 and Big city has an area of about 25.3 km^2. In our original paper, we just estimate the novel view synthesis performance on the small city maps. If you only want to test your reconstruction method, you can only download the small city images.
2. "Train_dense" data is sampled every 1 m and "train" data is sampled every 5 m.
3. Because the depth map and normal map of big city is too large, we just upload the depth map of small city. If you request, we can upload the depth maps.

**Comment by CJCHEN1230** [comment]
Hi, the topic i'm doing need  more diverse data. That would be grateful if you upload the depth map. Really appreciate!!
I have one more question.
4. Why there is a folder called "aerial_street_fusion" in the same level as big city but with smaller data number.

**Comment by yixuanli98** [comment]
I will upload the depth of big city. Please be patient. 
4. Please refer to Section 4.5 of our paper.

**Comment by yixuanli98** [comment]
You can first use the data of small city

**Comment by yixuanli98** [comment]
> Hi, the topic i'm doing need more diverse data. That would be grateful if you upload the depth map. Really appreciate!! I have one more question. 4. Why there is a folder called "aerial_street_fusion" in the same level as big city but with small amounts of data.

I have already uploaded the depth map of Big City. Just for your reference.
